datasets:
  ETTh1:
    root_path: ./dataset/ETT-small/
    data_path: ETTh1.csv
    txt_path:  ETTh1.csv
    data_name: etth1
    data: ett_h
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ETTh2:
    root_path: ./dataset/ETT-small/
    data_path: ETTh2.csv
    txt_path:  ETTh2.csv
    data_name: etth2
    data: ett_h
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ETTm1:
    root_path: ./dataset/ETT-small/
    data_path: ETTm1.csv
    txt_path:  ETTm1.csv
    data_name: ettm1
    data: ett_m
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ETTm2:
    root_path: ./dataset/ETT-small/
    data_path: ETTm2.csv
    txt_path:  ETTm2.csv
    data_name: ettm2
    data: ett_m
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  traffic:
    root_path: ./dataset/traffic/
    data_path: traffic.csv
    txt_path:  traffic.csv
    data_name: traffic
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  weather:
    root_path: ./dataset/weather/
    data_path: weather.csv
    txt_path:  weather.csv
    data_name: weather
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  electricity:
    root_path: ./dataset/electricity/
    data_path: electricity.csv
    txt_path:  electricity.csv
    data_name: electricity
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  ILI:
    root_path: ./dataset/illness/
    data_path: national_illness.csv
    data_name: ILI
    data: custom
    lradj: type4 
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100 
  exchange:
    root_path: ./dataset/exchange_rate/
    data_path: exchange_rate.csv
    data_name: exchange
    data: custom
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  aq:
    root_path: ./data_CSDI_miss/
    data_path: aq/AirQualityUCI_no_missing.csv
    txt_path:  aq/AirQualityUCI_mask.csv
    data_name: aq
    data: aq
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  nasdaq:
    root_path: ./data_CSDI_miss/
    data_path: nasdaq_top10.csv
    txt_path:  nasdaq_top10.csv
    data_name: nasdaq
    data: nasdaq
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  mimic:
    root_path: ./data_CSDI_miss/
    data_path: lab.csv
    txt_path:  lab.csv
    data_name: mimic
    data: mimic
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  physionet:
    root_path: ./data_CSDI_miss/
    data_path: set-a_icu
    txt_path:  set-a_icu
    data_name: physionet
    data: physionet
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_CA_FOODS:
    root_path: ./data_CSDI_miss/data
    data_path: FOODS_CA
    txt_path:  FOODS_CA
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_CA_HOBBIES:
    root_path: ./data_CSDI_miss/data
    data_path: HOBBIES_CA
    txt_path:  HOBBIES_CA
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_CA_HOUSEHOLD:
    root_path: ./data_CSDI_miss/data
    data_path: HOUSEHOLD_CA
    txt_path:  HOUSEHOLD_CA
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_TX_FOODS:
    root_path: ./data_CSDI_miss/data
    data_path: FOODS_TX
    txt_path:  FOODS_TX
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_TX_HOBBIES:
    root_path: ./data_CSDI_miss/data
    data_path: HOBBIES_TX
    txt_path:  HOBBIES_TX
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_TX_HOUSEHOLD:
    root_path: ./data_CSDI_miss/data
    data_path: HOUSEHOLD_TX
    txt_path:  HOUSEHOLD_TX
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_WI_FOODS:
    root_path: ./data_CSDI_miss/data
    data_path: FOODS_WI
    txt_path:  FOODS_WI
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_WI_HOBBIES: 
    root_path: ./data_CSDI_miss/data
    data_path: HOBBIES_WI
    txt_path:  HOBBIES_WI
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  M5_WI_HOUSEHOLD:
    root_path: ./data_CSDI_miss/data
    data_path: HOUSEHOLD_WI
    txt_path:  HOUSEHOLD_WI
    data_name: m5
    data: m5
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
  solar:
    root_path: ./data_CSDI_miss/data
    data_path: solar_nips/train
    txt_path:  solar_nips/train
    data_name: solar
    data: solar
    lradj: type4
    features: M
    target: OT
    embed: timeF
    freq: 0
    percent: 100
 